# Generated by Django 5.2.1 on 2025-05-30 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(unique_for_date='date', verbose_name='Hora de início')),
                ('end_time', models.TimeField(unique_for_date='date', verbose_name='Hora de término')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
