# Generated by Django 5.2.1 on 2025-05-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
    ]
