# Generated by Django 5.2.1 on 2025-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpayable',
            name='pending_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingpayable',
            name='settled_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingpayable',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingreceivable',
            name='pending_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingreceivable',
            name='settled_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingreceivable',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingpayable',
            name='installment_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billingpayable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('settled', 'Liquidado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingreceivable',
            name='installment_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billingreceivable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('settled', 'Liquidado')], default='pending', max_length=20),
        ),
    ]
