# Generated by Django 5.2.1 on 2025-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('color', models.CharField(max_length=10, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tag de Cliente',
                'verbose_name_plural': 'Tags de Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(to='clients.clienttag', verbose_name='Tags'),
        ),
    ]
