# Generated by Django 5.2.1 on 2025-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clienttag_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, to='clients.clienttag', verbose_name='Tags'),
        ),
    ]
